### PR TITLE
REVIEW ONLY Features/patterns

### PR DESCRIPTION
**Pull request by gafter**

### CODE REVIEW

**Comment by alrz** [comment]
damn you are fast! Can I ask you why not introducing a new keyword in match expression is so important but `let` is still a reasonable addition while we can use `is` as a statement? hope you don't mind that I commented here.

**Comment by gafter** [comment]
@alrz Perhaps you're proposing

``` cs
    is x = 12;
```

be the _let-statement_?

**Comment by alrz** [comment]
actually, this one wouldn't be categorized as "why not" because it exists! 

I'm proposing the existing `is` operator as statement,

``` cs
t is (var p, var q);
```

The fact that `void operator is` would be used in `let` doesn't feel right.

**Comment by gafter** [comment]
@alrz I would not prefer that because
- As an _expression-statement_, it has the wrong scoping rules. As a separate statement that just _looks_ like an _expression-statement_ but has different scoping rules, that would be confusing.
- It lacks the equivalent of the _let-statement_'s else.
- Since the purpose is to place bindings in the enclosing scope, the pattern should be on the left. It looks "wrong" for even the most basic use cases:

``` cs
let x = 12; // looks good
12 is var x; // WTF?

let (var longitude, var latitude) = GetCoords(); // looks good
GetCoords() is (var longitude, var latitude); // WTF?
```

**Comment by alrz** [comment]
I see. your examples totally convinced me. thank you.

**Pull request merged**
